### ISSUE TITLE
Unirom 8.0k w/ Caetla will not apply GameShark Codes (settings will not save either 256-512k ROM cart)

### ISSUE THREAD

**Issue by JMaxxL** [JonathanDotCel/unirom8_bootdisc_and_firmware_for_ps1#22]
Caetla bundled with 8.0k or 8.0J will not save gameshark codes or apply after booting. No settings codes or options save when useing cheat cart tried multiple 512k rom carts.

8.0K Caetla is not in english (please change language back to english or add option to select which Caetla version to install)
"Switch to Caetla 0.38 by default" < update comment from J to K

8.0J is in English but has same issue were gameshark codes or settings to not save or apply when installing UniROM w/Caetla

**Comment by JonathanDotCel** [comment]
Hi,
yep, this version of caetla uses the memory cards by default - which is not ideal. Next version will be back as it was. Cheers.

**Comment by JMaxxL** [comment]
ok because i keep tonyhax in slot two is this causing my issue possible, Im pretty sure I did boot up atleast once without it in slot 2

**Comment by JMaxxL** [comment]
O a "gameshark memory card" Im sorry... Ive looked for quite a while I cant find any gameshark code memory card images .MCD

**Comment by JonathanDotCel** [comment]
I don't have a ton of info on the format, tbh - you might have to do some hunting (maybe check https://psx.dev discord?)
But it def stored stuff on the memcard instead of on the cart's flash chip.

**Comment by JMaxxL** [comment]
yeah I've checked PSX.dev for sure for gameshark memcard images. I'm happy to just have flashcart for most games but I figured if work had been done to get caetla to work id like to use it. ive used CDX GS/AR CDs they hang right after booting the game 

Thanks ! for all the work I use UniROM almost daily on my cheatcarts is there a discord or donation link anywhere

**Comment by JMaxxL** [comment]
I was going to order a gameshark memory card looks like the actin replay version is cheaper will either of them work with caetla? looks like all they are is a normal memory card with a un-deleteable files right?

**Comment by JonathanDotCel** [comment]
Heh, I'm actually not really sure if there are any good collections of memcard cheats, etc!
No donation link, but give something to a charity if you like.

https://www.psx.dev/ has a discord link, maybe someone will have more info about the caetla cheats?
