### ISSUE TITLE
guide request 

### ISSUE THREAD

**Issue by dananothername** [JonathanDotCel/unirom8_bootdisc_and_firmware_for_ps1#26]
can i burn this to cd 
then use disk swap trick
then inside the psx copy free psxboot to the memory card 
or there is something better 
also i don't have cart cridge 
and the free psxboot is not installed in the sd card

**Comment by JonathanDotCel** [comment]
Hi dan,
yep, that's how you'd do it.

Follow this guide:
https://unirom.github.io/installation/#installing-from-cd

Then from the install menu, install to a memory card.

Cheers.
