### ISSUE TITLE
PoPoLoCrois Monogatari II (Japan) CR-R backup will not boot Software Terminated

### ISSUE THREAD

**Issue by JMaxxL** [JonathanDotCel/unirom8_bootdisc_and_firmware_for_ps1#29]
SCPS_101.12;1 (Disc 1)
SCPH-7501
Verbatim CD-R@1x
Gameshark 3.2 512k Datel V3 Flashed w/ UniROM 8.0k

![software terminated console may have been mo](https://user-images.githubusercontent.com/78325531/232598576-f7635586-74e0-49c6-ae64-bf3cc1b629d9.jpg)

![SCPS_101 12;1](https://user-images.githubusercontent.com/78325531/232598592-139bd701-4f12-4163-84cd-a9a4c3f3d53c.jpg)

**Comment by JonathanDotCel** [comment]
No worries, this too will be patched shortly.
Cheers :)
J
