### ISSUE TITLE
Rockman 2 (japan import) backup will not boot

### ISSUE THREAD

**Issue by JMaxxL** [JonathanDotCel/unirom8_bootdisc_and_firmware_for_ps1#31]
Rockman 2 jap import will not boot just get message console may have been modified 

Tried UniROM on flashed cheatcart proAR 128 "AMTEL 29C010A"
SCPH-7501 console - verbatium CD-R @1x

**Comment by JonathanDotCel** [comment]
Heyoo
plan to add patches for this after open sourcing (soonish).
