### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by Anonymous941** [JonathanDotCel/unirom8_bootdisc_and_firmware_for_ps1#32]
It's been a few years since you've been prepping the source code for release, can you consider releasing it soon?  Thanks

**Comment by ramapcsx2** [comment]
It is in preparation. Let the man breathe please :)

**Comment by Anonymous941** [comment]
Sorry to bother you again, but is there an ETR?  I can test with my SCPH-7501 if it helps...
