### ISSUE TITLE
GT2 NTSC Freeze

### ISSUE THREAD

**Issue by Jenmacik** [JonathanDotCel/unirom8_bootdisc_and_firmware_for_ps1#7]
Hi! I recently burned a NTSC copy of Gran Turismo 2 (Arcade Mode disc), however when launching via UROM it just freezes on a black screen after the intro fmv. Via swap trick it works fine...

**Comment by LostSoul1998** [comment]
Oops- opened this issue on my old account-

**Comment by JonathanDotCel** [comment]
Aweome, sounds like a good test case - thanks.
The next release has a slightly updated boot sequence, I'll test that and get back to you.

**Comment by JonathanDotCel** [comment]
Working again in 8.0.K (later today), thanks :)
