### ISSUE TITLE
Bishi Bashi Special (PAL) boots into a black screen

### ISSUE THREAD

**Issue by Kodden585** [JonathanDotCel/unirom8_bootdisc_and_firmware_for_ps1#8]
As I said, Bishi Bashi Special boots into a black screen. This actually happens with the NTSC-J game of the same name as well, but the PAL game is actually two games in a compilation.

**Comment by JonathanDotCel** [comment]
Hi, I've just double checked and both are working great for 8.0.K (sooon).
There's been some changes to the boot routine, so I'll mark this as closed now, but feel free to reopen the issue if it pops up again.
