### ISSUE TITLE
Update from memory card

### ISSUE THREAD

**Issue by Kodden585** [JonathanDotCel/unirom8_bootdisc_and_firmware_for_ps1#9]
Since it's now possible to update UniROM without having to boot into an install disc, wouldn't it be reasonable to be able to install an update from a memory card, rather than having to burn a CD for every update? Should at least be possible with the MemCard Pro.

**Comment by JonathanDotCel** [comment]
Yeah, this makes good sense - I've made a note to add it in the next release :)

**Comment by JonathanDotCel** [comment]
8.0.K (later today) allows backup/restore from memcard.
Gimme a shout if you hit any issues with that.
